AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  UserTableName:
    Type: String
    Default: LastSecond-MemoryStack-dev-UserTable

Globals:
  Function:
    Runtime: go1.x
    Timeout: 10
    Handler: main

Resources:
  getUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/get_user/main.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTableName
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user
            Method: GET

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref UserTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
